# err0.py
try:
    x = int(input("Введите число: "))
    print(5/x)
except:
    print("В процессе выполнения программы произошла какая-то ошибка.") 
